spring.datasource.url=jdbc:postgresql://localhost:5432/chesstomic
spring.datasource.username=admin
spring.datasource.password=chesstomic_pass

# Hibernate 6 detecta el dialecto automáticamente si detecta la librería spatial
spring.jpa.database=postgresql
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true